#!/bin/bash
# github_forklar hesap_ismi repo_ismi şeklinde kullanılır.
# /tmp/ altına repo_ismi_forklar dosyası oluşturur.
hesap=$1
repo=$2
cd /tmp
curl -s https://api.github.com/repos/$hesap/$repo/forks -o /tmp/${repo}_forks
cat ${repo}_forks | grep clone_url | awk '{print $2}' | sed s'/.$//' > ${repo}_forklar
cat ${repo}_forklar
